### ISSUE TITLE
Server seems like it can crash if client misbehaves or is missing

### ISSUE THREAD

**Issue by athas** [diku-dk/futhark-playground#12]
This happened after I clicked the Compile button when no client was available:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/ubuntu/gits/futhark-playground/web-server/socket_server.py", line 106, in run
    client_connection.run()
  File "/home/ubuntu/gits/futhark-playground/web-server/socket_server.py", line 45, in run
    self.job_queue.response_queue.put(parse_incoming(self.clientsocket))
  File "/home/ubuntu/gits/futhark-playground/web-server/socket_server.py", line 14, in parse_incoming
    incoming = socket_util.read_incoming(socket).decode("utf-8")
  File "/home/ubuntu/gits/futhark-playground/web-server/socket_util.py", line 42, in read_incoming
    size = bytes_to_int(socket.recv(1))
  File "/home/ubuntu/gits/futhark-playground/web-server/socket_util.py", line 11, in bytes_to_int
    i = b[0]
IndexError: index out of range
```

And then the server stopped listening for connections.

**Comment by Lukires** [comment]
I have tried to address this issue in my latest commit https://github.com/diku-dk/futhark-playground/commit/2b90a2560822d9e241be11df68c0781fa5299c7f

Please inform me if the issue persists.
